### ISSUE TITLE
question about swap_required_possible

### ISSUE THREAD

**Issue by ShuaiZhou302** [Kei18/lacam2#11]
Hello sir, i have problem understanding the for loop here 
![image](https://github.com/user-attachments/assets/df3a6694-bf84-4e8c-b5e2-3a3b2f8a7e57)
why does it consider agent ak and assume it is at ai->v_now and assume ai is at C[0]  and check if they can swap?    
If there is a demo help understanding this part?
Thank you so much

**Comment by Kei18** [comment]
Refer to Figure 6c. Agent 2 must behave non-greedy, and the highlighted part implements this. 

I acknowledge that this part is "dirty"; tuning was required to avoid corner cases.

**Comment by ShuaiZhou302** [comment]
thank you sir , but I am confused by this scenario:    1.Q_to [k] <- Q_from[i] ,  then agent k priority inheritance to agent i,  2.  agent i check swap_required and possible,  get an agent j , reverse the C.  3.  at C[0]  of agent i ,  Q_to[j] = null , then Qto[j]  <- Q_from[i],  then return valid,  4. the procedure now back to agent k,  it got valid result from agent i and return valid.  5. at this time, both Q_to[j] and Q_to[k] is assigned Q_from[i],  then it seems like a collision happened here?   
![image](https://github.com/user-attachments/assets/cf4d8c31-80b0-4212-84fb-cb2e16b82729)

**Comment by Kei18** [comment]
Ah, I see. The pseudocode is missing this line! I indeed did a collision check.
https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L364

Thanks, I was not aware of this. I will show this errata on the project page.

**Comment by ShuaiZhou302** [comment]
Thank you sir. Its my pleasure
