### ISSUE TITLE
Question about swap concept and functions

### ISSUE THREAD

**Issue by ShuaiZhou302** [Kei18/lacam2#12]
Hello sir, sorry to bother you again.
I have two questions about swap part.
1.  first is about the is_swap_required: 
![image](https://github.com/user-attachments/assets/26d83fed-04f1-4381-9201-144f3babb8fd)
There are two scenarios for while loop to break; one is n <=0; the other is  D.get(pusher, v_puller) >= D.get(pusher, v_pusher). 
At scenrio one, n <= 0 leaves the shilw loop with promise of D.get(pusher, v_puller) < D.get(pusher, v_pusher).  At scenario 2.  after the assigment of v_pusher and v_puller in the end of while loop,  D.get(pusher, v_puller) >= D.get(pusher, v_pusher).  But this case only happened when v_pusher arrives goal and v_puller is one step away from v_pusher's goal.   Consider this two scenarios, the second judgement of return is automatically satisfied, (D.get(pusher, v_pusher) == 0 || D.get(pusher, v_puller) < D.get(pusher, v_pusher)); Is this judegement  redundant?.
2.  My second question is : By my observation.  is_swap_required is like a procedure check if "push" can solve this exchange of position. and if it dont.  is_swap_possible will check if "pull" can solve this cases.  
![image](https://github.com/user-attachments/assets/a9353699-fe5d-40f8-95c3-88213810924c)
And why can we do a logical negation for this two function.  for example,  Completely copy the part of is_swap_possible to is_swap_required, only change return true to  return false, return false to return true, and when call this two functions, we only switch the position of pusher and puller.   And of course your code dont work like this, So my question is , why this two function is not logically negation. 
I didn't quite get these from your paper, I will be very grateful if you can reply to me. Thank you!

**Comment by Kei18** [comment]
1. With only two agents, yes, the last line is probably redundant. But with more than three agents, according to the priority inheritance scheme, I encountered some unfavourable corner cases. Basically, I wanted to minimise the number of swaps for performance reasons; the last check does that.

2. The first function determines if a swap is required, while the second determines if a swap is possible - they are not logically negation, so the implementation can be different. During development, I also tested your idea of just swapping true/false and puller/pusher. It generally worked as far as I remember, but to maximise the performance, I updated to the current one. There were many corner cases that are hard to describe.

Please note that this is an implementation-sensitive part that needs to be fine-tuned to avoid corner cases as much as possible. You can be different.

**Comment by ShuaiZhou302** [comment]
Thank you！
