### ISSUE TITLE
some changes in code

### ISSUE THREAD

**Issue by sirius-zyj** [Kei18/lacam2#9]
If at time T, an agent occupies a grid, then at time T+1, no other agent except the occupant itself can move to this grid. 
In this case, how can I edit the code?

**Comment by Kei18** [comment]
Hi, I think it is doable. Below is a short guideline.

- LaCAM(*) uses PIBT as a configuration generator
- Except for the swap operation, PIBT can prohibit such conflicts by adding a few lines, c.f., 
  - [vertex conflict](https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L346)
  - [swap conflict](https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L351)
- And, do not forget to add [constraints to LaCAM itself]( https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L295-L301)
- I do not have a short answer for the swap operation. At first, it is better to drop it. Seems complicated.

**Comment by sirius-zyj** [comment]
Thank you very much for your advice. 
Based on my understanding of the algorithm, I added the PIBT conflict constraint and LACAM constraint as follows. 
![image](https://github.com/Kei18/lacam2/assets/62042039/8e3bc5fc-2975-49d9-bee8-b44de564aa21)
![image](https://github.com/Kei18/lacam2/assets/62042039/b9e2fedd-c0d1-4c60-93e0-da7835c9bf22)
However, the results of the code execution are rather strange.
I hope you can help correct it when you have time.

**Comment by Kei18** [comment]
The following is a minimum working example.

constraints for LaCAM
https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L290

```cpp
  // add constraints
  for (uint k = 0; k < L->depth; ++k) {
    const auto i = L->who[k];        // agent
    const auto l = L->where[k]->id;  // loc

    // check vertex collision
    if (occupied_next[l] != nullptr) return false;

    // check following collision
    if (occupied_now[l] != nullptr && i != occupied_now[l]->id) return false;

    // set occupied_next
    A[i]->v_next = L->where[k];
    occupied_next[l] = A[i];
  }
```

PIBT
https://github.com/Kei18/lacam2/blob/dev/lacam2/src/planner.cpp#L342

```cpp
  // PIBT operation
  for (auto k = 0; k < K + 1; ++k) {
    auto u = C_next[i][k];

    // avoid vertex conflicts
    if (occupied_next[u->id] != nullptr) continue;

    auto& ak = occupied_now[u->id];

    // avoid following conflicts
    if (ak != ai && ak != nullptr) continue;

    // reserve next location
    occupied_next[u->id] = ai;
    ai->v_next = u;

    // success to plan next one step
    return true;
  }
```

Please note that this is a toy example. To elicit the performance of LaCAM, you need to improve the performance of the PIBT part; Indeed, the above is just doing prioritized planning with a single-step window (and empirically shown bad in the AAAI-23 paper)
